#extensions
dot pie: ".py"
dot (talon|town): ".talon"
dot mark down: ".md"
dot text: ".txt"
dot shell: ".sh"
dot vim: ".vim"
#dot see: ".c"
dot see sharp: ".cs"
dot com: ".com"
dot net: ".net"
dot org: ".org"
dot exe: ".exe"
dot (bin | bend): ".bin"	
dot (jason | jay son): ".json"
dot git: ".git"