talon (history|log): user.history_toggle()
talon (history|log) show: user.history_enable()
talon (history|log) hide: user.history_disable()
talon (history|log) clear: user.history_clear()
talon (history|log) less: user.history_less()
talon (history|log) more: user.history_more()
