talon history: user.history_toggle()
talon history show: user.history_enable()
talon history hide: user.history_disable()
talon history clear: user.history_clear()
talon history less: user.history_less()
talon history more: user.history_more()
