command history show: user.history_enable()
command history hide: user.history_disable()
command history clear: user.history_clear()
command history more: user.history_more()
command history less: user.history_less()
