#<user.arrows>: key(arrows)
<user.arrow>: key(arrow)
<user.number>: key(number)
<user.letter>: key(letter)
capital <user.letters> [over|lower]:
    user.keys_uppercase_letters(letters)
<user.symbol>: key(symbol)
<user.function>: key(function)
<user.special>: key(special)
<user.key>: key(key)
