volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
volume (mute|toggle) | (mute|toggle) volume: key(mute)
play next: key(next)
play previous: key(prev)
(play | pause) that: key(play)
